#
#  Copyright (c) 2016 CA. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '2'
services:
  mas:
    extends:
      file: MAG-docker-compose.yml
      service: mag
    image: ${IMAGE}
    ports:
      - "8883:8883"
    hostname: ${MAS_HOSTNAME}
    environment:
      - MAS_STORAGE_ENABLED
      - MAS_MESSAGING_ENABLED
      - MAS_IDENTITY_ENABLED
      - DEV_CONSOLE_ENABLED
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_HOST
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_PORT
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_USER
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_PASSWORD
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_NAME
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_TYPE
      - BUNDLE_TEMPLATE_IDENTITY_DATABASE_MYSQL_ENABLED
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_HOST
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_PORT
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_USER
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_PASSWORD
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_NAME
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_TYPE
      - BUNDLE_TEMPLATE_STORAGE_DATABASE_MYSQL_ENABLED
      - BUNDLE_TEMPLATE_MESSAGING_BROKER_HOST
      - BUNDLE_TEMPLATE_MESSAGING_BROKER_PORT
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_HOST
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_PORT
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_USER
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_PASSWORD
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_NAME
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_TYPE
      - BUNDLE_TEMPLATE_DEV_CONSOLE_DATABASE_MYSQL_ENABLED
      - ADD_TEST_USERS_GROUPS
